#!/usr/bin/env python3
import sys, json
from jsonschema import Draft202012Validator
if len(sys.argv) != 2:
    print("Usage: json_schema_check.py <schema.json>")
    sys.exit(2)
with open(sys.argv[1], "r", encoding="utf-8") as f:
    schema = json.load(f)
Draft202012Validator.check_schema(schema)
print("SCHEMA: PASS")
