name: KAIROS CI
on:
  workflow_dispatch: {}

jobs:
  smoke:
    name: KAIROS CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env: { PYTHONUTF8: "1" }
    steps:
      - name: Настроить работу
        uses: actions/checkout@v4
      - name: Показать дерево
        run: |
          echo "::group::tree-root"; ls -la; echo "::endgroup::"
          echo "::group::tree-KAIROS"
          ls -la 08-agents || true
          ls -la 08-agents/KAIROS || true
          echo "::endgroup::"
      - name: Пути проверки работоспособности (строго)
        run: |
          set -euo pipefail
          for p in \
            "08-agents/KAIROS/.pre-commit-config.yaml" \
            "08-agents/KAIROS/Makefile" \
            "08-agents/KAIROS/scripts/json_schema_check.py" \
            "08-agents/KAIROS/scripts/nr_fm.py"
          do
            [ -f "$p" ] && echo "OK $p" || { echo "::error::MISS $p"; exit 1; }
          done
      - name: Python deps
        uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: 'pip' }
      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml
      - name: Самопроверка схемы
        run: python 08-agents/KAIROS/scripts/json_schema_check.py
      - name: Проверка фронтматтера/фикстур
        run: python 08-agents/KAIROS/scripts/nr_fm.py --check
