name: KAIROS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch: {}   # ручной запуск

permissions:
  contents: read

jobs:
  precommit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit (all files)
        run: pre-commit run --all-files
        working-directory: 08-agents/KAIROS

  validation:
    name: validation
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Schema check
        run: python3 scripts/json_schema_check.py schemas/frontmatter.schema.json
        working-directory: 08-agents/KAIROS
      - name: Frontmatter fixtures validate
        run: python3 scripts/nr_fm.py tests/fixtures/frontmatter
        working-directory: 08-agents/KAIROS
      - name: CI validate (stub)
        run: make ci-validate
        working-directory: 08-agents/KAIROS
      - name: Upload observability logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kairos-logs
          path: |
            08-agents/KAIROS/observability/logs/*
          if-no-files-found: ignore
