name: KAIROS CI

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/kairos-ci.yml'
      - '08-agents/**'
      - 'schemas/**'
      - 'pipelines/**'
      - 'requirements.txt'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/kairos-ci.yml'
      - '08-agents/**'
      - 'schemas/**'
      - 'pipelines/**'
      - 'requirements.txt'
      - 'pyproject.toml'

permissions:
  contents: read

concurrency:
  group: kairos-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kairos:
    name: KAIROS CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        shell: bash
        run: |
          echo "::group::tree-root"; ls -la; echo "::endgroup::"
          echo "::group::tree-08-agents"; ls -la 08-agents || true; echo "::endgroup::"
          echo "::group::tree-KAIROS"; ls -la 08-agents/KAIROS || true; echo "::endgroup::"

      - name: Sanity verify paths (strict)
        shell: bash
        run: |
          set -euo pipefail
          for p in \
            "08-agents/KAIROS/Makefile" \
            "08-agents/KAIROS/scripts/json_schema_check.py" \
            "08-agents/KAIROS/scripts/nr_fm.py"
          do
            if [ -f "$p" ]; then
              echo "OK $p"
            else
              echo "::error::MISS $p"; exit 1
            fi
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (if present)
        if: ${{ hashFiles('**/requirements.txt', '**/pyproject.toml') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install -e .
          fi

      - name: Dependencies not found — skip install
        if: ${{ hashFiles('**/requirements.txt', '**/pyproject.toml') == '' }}
        run: echo "No requirements.txt / pyproject.toml — skipping dependency install."

      - name: Spec vs workflow sync check
        shell: bash
        run: |
          set -euo pipefail
          python 08-agents/KAIROS/scripts/ci_spec_check.py \
            --spec 08-agents/KAIROS/pipelines/validation_ci.spec.yaml \
            --workflow .github/workflows/kairos-ci.yml

      - name: Schema self-check (strict)
        if: ${{ hashFiles('08-agents/KAIROS/schemas/frontmatter.schema.json') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import json
          from jsonschema import Draft202012Validator
          p = '08-agents/KAIROS/schemas/frontmatter.schema.json'
          with open(p, 'r', encoding='utf-8') as f:
              schema = json.load(f)
          Draft202012Validator.check_schema(schema)
          print("schema OK:", p)
          PY

      - name: Fixture validate (frontmatter, with summary)
        if: ${{ hashFiles('08-agents/KAIROS/tests/fixtures/frontmatter/good/*.json') != '' || hashFiles('08-agents/KAIROS/tests/fixtures/frontmatter/bad/*.json') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p 08-agents/KAIROS/observability
          python 08-agents/KAIROS/scripts/nr_fm.py \
            --schema 08-agents/KAIROS/schemas/frontmatter.schema.json \
            --base   08-agents/KAIROS/tests/fixtures/frontmatter \
            --output json \
            --summary 08-agents/KAIROS/observability/fm_summary.json \
            --gh-summary

      - name: Upload fm-summary artifact
        if: ${{ hashFiles('08-agents/KAIROS/observability/fm_summary.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: fm-summary
          path: 08-agents/KAIROS/observability/fm_summary.json
          if-no-files-found: error

      - name: Make ci-validate (if present)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f 08-agents/KAIROS/Makefile ]; then
            if grep -qE '^\s*ci-validate\s*:' 08-agents/KAIROS/Makefile; then
              make -C 08-agents/KAIROS ci-validate
            else
              echo "No 'ci-validate' target — skipping."
            fi
          else
            echo "Makefile not found — skipping."
          fi
