name: KAIROS Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release tag (e.g. v0.3.0)"
        required: true
        type: string
      notes:
        description: "Optional release notes"
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if present)
        if: ${{ hashFiles('**/requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Schema self-check (strict)
        run: |
          python 08-agents/KAIROS/scripts/json_schema_check.py             08-agents/KAIROS/schemas/frontmatter.schema.json

      - name: Fixture validate (frontmatter, with summary)
        run: |
          python 08-agents/KAIROS/scripts/nr_fm.py             --schema 08-agents/KAIROS/schemas/frontmatter.schema.json             --base   08-agents/KAIROS/tests/fixtures/frontmatter             --summary 08-agents/KAIROS/observability/fm_summary.json             --gh-summary

      - name: Upload fm-summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: fm-summary
          path: 08-agents/KAIROS/observability/fm_summary.json
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.notes }}
          draft: false
          prerelease: false
          files: |
            08-agents/KAIROS/observability/fm_summary.json
