name: KAIROS Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare archive
        run: |
          mkdir -p dist
          zip -r dist/KAIROS_${{ github.ref_name }}.zip 08-agents/KAIROS
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KAIROS_${{ github.ref_name }}
          path: dist/KAIROS_${{ github.ref_name }}.zip
