name: Secrets Scan

on:
  workflow_dispatch:
  push:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
